### ISSUE TITLE
AadController#getUsernamesFromGraph throws Exception

### ISSUE THREAD

**Issue by miztaka** [Azure-Samples/active-directory-java-webapp-openidconnect#1]
I tried this sample, and got an error bellow:
ERROR PAGE!
Exception - java.io.IOException: Server returned HTTP response code: 403 for URL: https://graph.windows.net/XXXXXXXXXX.onmicrosoft.com/users?api-version=2013-04-05

it seems SSO was successful but throws Exception at getUsernamesFromGraph.

Any suggestions ?

**Comment by chenbp1982** [comment]
I also have the error below : 
ERROR PAGE!
Exception - java.io.IOException: Server returned HTTP response code: 403 for URL: https://graph.windows.net/XXXXXXXXXX.onmicrosoft.com/users?api-version=2013-04-05

**Comment by lhervier** [comment]
Youy need to give appropriate access rights to your application in the AD.
See http://stackoverflow.com/questions/38735655/graph-api-in-sso-is-not-working-in-azure-ad

**Comment by prli** [comment]
The stackoverflow answer did not solve the issue.

**Comment by jpirir** [comment]
> I follow this answer, i don't granted the permissions 
[https://github.com/Azure-Samples/active-directory-java-webapp-openidconnect/issues/2#issuecomment-307106854](https://github.com/Azure-Samples/active-directory-java-webapp-openidconnect/issues/2#issuecomment-307106854)

**Comment by abbhhiisseek** [comment]
Even if all permissions are granted in Azure, still HTTP response code: 403 remains.

**Comment by navyasric** [comment]
The sample has been updated to call MS Graph and the Readme has also been updated. 
Please reopen if the issue repeats.

**Comment by abbhhiisseek** [comment]
Hi Navya,

Thank you for the mail.
The sample is working fine now.

However, the below issue still exists.
Request parameters are chopped off after authentication redirect leading to
incorrect URLs.

Thanks and regards,
Abhisek Banerjee

**Comment by jmprieur** [comment]
@sangonzal FYI
