### ISSUE TITLE
AADSTS50011: The reply address does not match the reply addresses configured for the application

### ISSUE THREAD

**Issue by ShirleyCAT2016** [Azure-Samples/active-directory-java-webapp-openidconnect#11]
Hi,

I followed all the steps, when I click "Show users in the tenant", I logged in with correct username/password, but got the following error:

AADSTS50011: The reply address 'http://40.125.214.109:8080/adal4jsample/secure/aad' does not match the reply addresses configured for the application: 'e7600f19-2ec1-43c3-ad45-18bce3371553'. More details: not specified.

I set the "Reply URLs" in Azure portal, as "http://40.125.214.109:8080/adal4jsample/".

Any hints?

**Comment by AntonChernysh** [comment]
Same, I think Im doing something wront. 
When I enter blabla/secure/aad it ends un in infinite redirect loop.

**Comment by jmprieur** [comment]
did you add the reply URL in the "Reply URLs" section for the application in the [Azure portal](https://portal.azure.com) ?
Go to your application | Settings | Reply URLs
![image](https://user-images.githubusercontent.com/13203188/36058420-bda170fa-0e1f-11e8-90aa-0c703a27abfe.png)

**Comment by BlueClouDragon** [comment]
I have met an error like this:

AADSTS50011: The reply address 'https://10.99.1.234:4200/user#id_token=emptyJwt&state=%2f&session_state=2ac7d60c-cdd1-433c-93fa-3c92cb6e20b8' does not match the reply addresses configured for the application: '58b439a3-54d6-42b2-b80e-804fa750c074'. More details: not specified

If I remove #id_token~6e20b8 in the browser and refresh it, success sign into Azure AD

**Comment by BlueClouDragon** [comment]
please help me...
I have inserted in portal reply URI  ->  "'https://10.99.1.234:4200/user"

**Comment by navyasric** [comment]
@BlueClouDragon The reply URL you register  in the Azure portal should match the reply URL to which your application redirects after successful login with Azure AD. Please check the updated instructions in the Readme. Closing the issue for now. Reopen if necessary.

**Comment by solokingjec** [comment]
When testing on localhost, the integration worked fine.. I was able to login and get redirected to a secured page. I deployed the same code to a server with https and am getting into an infinite loop. Any help will be greatly appreciated. I can share my project and also create a test server

**Comment by TiagoBrenck** [comment]
@solokingjec are you receiving the error message, **AADSTS50011: The reply address does not match the reply addresses configured for the application?**
If so, how come you are in a loop? Could you please explain more about your problem? Or, if your problem is not related to this topic, do you mind opening a new one?

**Comment by solokingjec** [comment]
If you don't mind, I can give you access to the app on the server with the login details, also the project itself. Am in a very desperate situation

**Comment by motolola** [comment]
I have same issue for my app ... I can't even see the settings area  to set reply url like most other interfaces. Even though I created the app, I didn't create the company's Azure portal.

**Comment by jmprieur** [comment]
You need to have 'http://40.125.214.109:8080/adal4jsample/secure/aad' as well
