### ISSUE TITLE
Weblogic server

### ISSUE THREAD

**Issue by jerryescom** [Azure-Samples/active-directory-java-webapp-openidconnect#15]
Hi

I would like to test the app in Weblogic server, however I´m getting an exception:
**com.nimbusds.jwt.JWT.getJWTClaimsSet()Lcom/nimbusds/jwt/ReadOnlyJWTClaimsSet;**

I´m able to deploy the war successfully, click on Show users in the tenant, write my credentials and submit them. After that, the exception above is shown.

Any idea?
![weblogicerror](https://user-images.githubusercontent.com/38109018/38388829-05cc383c-38e2-11e8-8368-52853bbe3a7f.jpg)

**Comment by navyasric** [comment]
@jerryescom The sample has been updated to use latest versions of the ADAL4J and the nimbus libraries. 
Please try the updated sample and reopen if the issue occurs again.
