### ISSUE TITLE
Request parameters are chopped off after authentication redirect leading to incorrect URLs

### ISSUE THREAD

**Issue by abbhhiisseek** [Azure-Samples/active-directory-java-webapp-openidconnect#17]
Sample URL before authentication
http://localhost:8080/openTransfer.htm?reqId=T123

After authentication redirect, the parameter **reqId=T123** is chopped leaving only http://localhost:8080/openTransfer.htm

Can you please look into this?

**Comment by sangonzal** [comment]
@abbhhiisseek What was the reply url that you registered in the AAD portal?

**Comment by abbhhiisseek** [comment]
@sagonzal The registered reply url is
http://localhost:8080/*

The parameter reqId=T123 is dynamic. There may be other parameter values as well.

**Comment by sangonzal** [comment]
Question was answered here: https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/211

Closing since question was answered. Feel free to re-open if you have any other questions.

**Comment by abbhhiisseek** [comment]
@sangonzal @psignoret
**I am sending queryString in stateData in sendAuthRedirect method (Basic Filter) before authentication**

        String state = "{\\"state\":\\"" + UUID.randomUUID().toString() +
        "\\",\\"queryString\\":\\"" + httpRequest.getQueryString() + "\\"}";
        

**and retrieving it from State after authentication and setting it as servletRequest attribute in processAuthenticationData method (Basic Filter)** 

        JSONParser parser = new JSONParser();
        JSONObject stateJson = (JSONObject) parser.parse(params.get(STATE));
        String queryStr = stateJson.get("queryString").toString();
        if(queryStr != null ){
        	httpRequest.setAttribute("key", queryStr);
        }

**Is this approach correct?**
