### ISSUE TITLE
Wrong or outdated info in README

### ISSUE THREAD

**Issue by Serg-Maximchuk** [Azure-Samples/active-directory-java-webapp-openidconnect#19]
There is wrong or outdated info in README file:
Step 3 -> Register the app app (Webapp-Openidconnect) -> 10th point:

> Then, click on **Select Permissions** and select **Directory.Read.All**.

I can't find such thing as `Directory.Read.All`, there are a lot of checkboxes. I've checked them all and demo works fine, but maybe I had to check only one permission that is renamed now?

**Comment by sangonzal** [comment]
@Serg-Maximchuk Thanks for pointing this out. The right permission should be `Read directory data` under `Application Permissions`. I have updated the README with these instructions.

**Comment by Serg-Maximchuk** [comment]
Thanks!
