### ISSUE TITLE
Where do I get the secret_key?

### ISSUE THREAD

**Issue by munseym** [Azure-Samples/active-directory-java-webapp-openidconnect#2]
I went to AD > appplications > myApp and generated a 1 year key.  But when I put this in my web.xml I get 403 errors in the sample app.  Is this not the key I am looking for?

**Comment by tushar-saxena** [comment]
I am also facing this issue.

**Comment by gsacavdm** [comment]
The details of where you got this key are a little vague (would be better if you shared a screenshot), but it sounds like you are using the right key. Double check by making sure you followed the steps outline in the **To add credentials, or permissions to access web APIs** section in the [Application Registration](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications) documentation.

Also, please add more details what endpoint you are hitting that you're getting 403, we're looking for HTTP requests, screenshots of errors, etc... as it stands it's hard to provide any help.

**Comment by jmprieur** [comment]
We have much improved the README.md (see bullet point 8 of Step 2)
