### ISSUE TITLE
About the Redirect URIs

### ISSUE THREAD

**Issue by arrebnac** [Azure-Samples/active-directory-java-webapp-openidconnect#22]
For step 8 of Register the app app (Webapp-Openidconnect)
The Redirect URIs, should we put it http://localhost:8080/adal4jsample/secure/aad ?
It seems if I keep the original one https://localhost:8000/adal4jsample/secure/aad, I will get 
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: error.
While if I change it to http://localhost:8080/adal4jsample/secure/aad, the program can run.

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
