### ISSUE TITLE
Need to Force Admin Consent before it works

### ISSUE THREAD

**Issue by groyal** [Azure-Samples/active-directory-java-webapp-openidconnect#23]
There is an extra step missing in the instructions. 

Read Directory requires Admin consent before it can talk to Graph API. 
You will get a 403 forbidden error. 

To force an admin consent you need do something like this: 
https://login.microsoftonline.com/nicksdemodir.onmicrosoft.com/oauth2/authorize?client_id=40dba662-4c53-4154-a5cf-976473306060&response_type=code&redirect_uri=sample://callback&nonce=1234&resource=https://graph.windows.net&prompt=admin_consent

1) Make sure you are logged out of your browser. 
2) goto the authenticate URL try to login. 
3) This will show the login screen with the Login URL. 
4) add "&prompt=admin_consent" to the end of the URL and reload
5) Accept Consent and you are good to go. 

This will force you to consent to the app talking to the Graph API. 
Then it will work for everyone.

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
