### ISSUE TITLE
Basic Filter Error in Java 1.8.0_91

### ISSUE THREAD

**Issue by abbhhiisseek** [Azure-Samples/active-directory-java-webapp-openidconnect#25]
**Compilation error in Line 125 and Line 126 of BasicFilter.java** without making any changes to rest of code 

**Line 125**  for (String key : httpRequest.getParameterMap().keySet()) {
            **Error** Type mismatch: cannot convert from element type Object to String
          
**Line 126**  params.put(key, httpRequest.getParameterMap().get(key)[0]);  
 **Error** The type of the expression must be an array type but it resolved to Object
        }

Can you please look into the above?

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
