### ISSUE TITLE
Integrating Azure AD into a Java web application using Service Principal

### ISSUE THREAD

**Issue by LincredibleD** [Azure-Samples/active-directory-java-webapp-openidconnect#28]
Hi, do you have an example where you integrate Azure AD into a Java web application using Service Principal? I am looking to embed PowerBI report in a Java web application. Thanks.

**Comment by navyasric** [comment]
You can find a list of Java samples here: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code
If I understand rightly, I believe you are looking for this sample: https://github.com/Azure-Samples/ms-identity-java-daemon

Anyhow,  there's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
