### ISSUE TITLE
This sample fails to compile with JDK12

### ISSUE THREAD

**Issue by mahoekst** [Azure-Samples/active-directory-java-webapp-openidconnect#29]
/C:/src/active-directory-java-webapp-openidconnect/src/main/java/com/microsoft/aad/adal4jsample/User.java:[30,33] package javax.xml.bind.annotation does not exist
[ERROR] /C:/src/active-directory-java-webapp-openidconnect/src/main/java/com/microsoft/aad/adal4jsample/User.java:[38,2] cannot find symbol
  symbol: class XmlRootElement

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
