### ISSUE TITLE
authenticate against on-premise OIDC server

### ISSUE THREAD

**Issue by mtuppad** [Azure-Samples/active-directory-java-webapp-openidconnect#30]
Can this library be used to authenticate against on-prem OIDC server. 

Currently when we use this library this is the flow that followed. 
1. User hits www.myapp.com
2. Since user is not authenticated, will redirected to Microsoft login page <<we need to avoid this>>
3. User enters email id and user is redirected to on prem OIDC end point - (Azure AD is configured this way) oidc-prod.mycorp.com 
4. user enters username and password, gets authenticated, and redirected back to myapp. 

We would like to skip step 2 and directly redirect to on-pre OIDC server? (apps can access this end point)

App is hosted in azure AKS.

**Comment by mtuppad** [comment]
I guess this is not the right place for this query. I have asked the same question at https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/262#issue-429102667

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
