### ISSUE TITLE
Only works on offline mode.

### ISSUE THREAD

**Issue by solokingjec** [Azure-Samples/active-directory-java-webapp-openidconnect#31]
On a production server, it gets into an infinite loop after signing.

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
