### ISSUE TITLE
403 Error on URL https://graph.microsoft.com/v1.0/users

### ISSUE THREAD

**Issue by sammycakes** [Azure-Samples/active-directory-java-webapp-openidconnect#32]
When I click "Show users in the tenant" and log in, I still get a 403 error ava.io.IOException: Server returned HTTP response code: 403 for URL: https://graph.microsoft.com/v1.0/users.

I think I've done everything from the instructions. In the portal, API permissions, I added Microsoft Graph Application permission for Directory.Read.All, and Granted admin consent for Default Directory so there's a green checkbox.

If I go to the owners page, I am the app owner, and I have role Global Administrator in my tenant.

The few things I'm not sure about: in web.xml, where we enter the tenant, the tenant can't possibly be the crazy Directory(tenant) ID which looks like a client ID or client secret, but the tenant is instead a value likely ending in onmicrosoft.com?

Also, I don't have a place for a sign-on URL or App ID URI in Azure...not sure if this is playing a role.

In the Authentication Tab of the App registration, I don't need any implicit grant selection (Access tokens or ID tokens), and under Default client type, I should NOT treat application as a public client (since this is required where a redirect URI is not used)?

Any other ideas?

Thanks so much,
Sam

**Comment by sangonzal** [comment]
@sammycakes Either tenantId or <your_tenant>.onmicrosoft.com should work. You don't need any implicit grant selection, and your app should be registered as a confidential/web application. 

Are you able to acquire a token successfully? Are [including this token](https://github.com/Azure-Samples/active-directory-java-webapp-openidconnect/blob/master/src/main/java/com/microsoft/aad/adal4jsample/AadController.java#L76) in the call to graph?

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
