### ISSUE TITLE
not able to run the application getting exception

### ISSUE THREAD

**Issue by JKeeru** [Azure-Samples/active-directory-java-webapp-openidconnect#34]
I have run the application and able to go to home page but on click of show users getting exception 
![image](https://user-images.githubusercontent.com/23631855/60280115-f41ba880-991f-11e9-87b8-ffccc92608f9.png)

and as i debugged the method which specifies it is there in the jar and jar is in build path still it throws method not found erron

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
