### ISSUE TITLE
Section 3 out of date

### ISSUE THREAD

**Issue by hemolack** [Azure-Samples/active-directory-java-webapp-openidconnect#35]
The app registration section will be out of date once App registrations (Legacy) is no longer usable.  Can the walk-through be updated to use the new App registrations functionality?

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
