### ISSUE TITLE
401 error getting

### ISSUE THREAD

**Issue by srikasulu** [Azure-Samples/active-directory-java-webapp-openidconnect#36]
When i am trying to  use aquretoken () - geting 401 error.  I have registered appservice in Active Directory properly.

Friends please give me guidance

**Comment by sangonzal** [comment]
@srikasulu I recommend you take a look at the [MSAL web sample](https://github.com/Azure-Samples/ms-identity-java-webapp). This has updated instructions and uses [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java), which is the recommended way to go if you are starting a new project.

**Comment by navyasric** [comment]
As mentioned above, there's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
