### ISSUE TITLE
Failed to validate data received from Authorization service - could not validate state

### ISSUE THREAD

**Issue by adarshrhegde** [Azure-Samples/active-directory-java-webapp-openidconnect#6]
When I test this code and click "Show users in tenant" one of the requests go to https://login.microsoftonline.com/tenantName/oauth2/authorize?response_type=code&scope=openid&response_mode=form_post&redirect_uri=https%3A%2F%2F10.62.137.70%2Fadal4jsample%2Fsecure%2Faad&client_id=266b8761-10e3-472c-828c-e18ee1d9bcd1&resource=https%3a%2f%2fgraph.windows.net&state=57251d61-0ab7-4694-b228-c7bf5dfa453a&nonce=4b22a3ac-6658-4fa3-b49d-15f69e37dfc3

This request is giving me a "Failed to validate data received from Authorization service - could not validate state" error on the browser.

**Comment by vzvince** [comment]
Hi @adarshrhegde , did you fix the issue now? I have the same error got.

**Comment by jmprieur** [comment]
@sangonzal can you please check with Petro if this is a known issue?

**Comment by sangonzal** [comment]
@SomkaPe Have you run into this issue before?

**Comment by guilhermebreed** [comment]
https://login.microsoftonline.com/openkad.onmicrosoft.com/oauth2/authorize?response_type=code&scope=directory.read.all&response_mode=form_post&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadal4jsample%2Fsecure%2Faad&client_id=a471e8f1-04e5-4452-a53e-0afa8d386148&resource=https%3a%2f%2fgraph.microsoft.com&state=a8f15e74-5154-4c5b-bc37-8e6e23c7f86c&nonce=4279d5cc-aa14-448d-9e14-e5cef6bc04c0

**I have the same error!!! Can someone help me?**

**Comment by hiteshghuge** [comment]
I works for me when I have deployed on separate instance of JBoss6.1.0 . But when I tried to move this to my application it return "**Failed to validate data received from Authorization service - could not validate state**".
After debugging I come to know its checking "**states**" parameter in session, but its missing in session.

Anybody got luck?

**Comment by navyasric** [comment]
There's a newer version of this sample taking advantage of the Microsoft identity platform (formerly Azure AD v2.0) and the latest MSAL Java library. Check it out: https://github.com/Azure-Samples/ms-identity-java-webapp. This is the most up to date and recommended sample to follow. You may ask further question on the new sample repo.

If you really need to access this Azure AD v1.0, you can navigate to the master branch, but please know that it's no longer supported.
Closing this issue as we are archiving this repo.
