### ISSUE TITLE
AuthenticationContext should provide the function to set the proxy credential ?

### ISSUE THREAD

**Issue by yushiutsai** [Azure-Samples/active-directory-java-webapp-openidconnect#9]
There are many proxy setting in our product. Azure cloud is one of them.The adal4j should provide the function to set the proxy credential, and not to use the properties in JVM.AWS SDK and vCloud SDK have the similar function to set the proxy credential.

If not, could you please provide work-around way for us?

Thanks
 
--

**Comment by SomkaPe** [comment]
you can set proxy authentication by using java.net.Authenticator, like this:

        Authenticator.setDefault(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("login", "password".toCharArray());
            }
        });

**Comment by navyasric** [comment]
@yushiutsai Closing this issue as it has been answered in above comment. You may reopen if necessary,
